language: node_js
node_js:
  - "4.4.1"
before_install:
  -  gem install sass
  -  npm install -g bower
  -  npm install -g grunt-cli
  -  sudo apt-get install imagemagick
  -  sudo apt-get install graphicsmagick-imagemagick-compat
install:
  - sudo npm install
  - sudo bower install
before_script: grunt
